In [1]:
import pandas as pd
import upsetplot as up
from matplotlib import pyplot

In [2]:
pd.set_option('display.max_rows', 500)

In [31]:
df = pd.read_csv("permutation_results_0.15_OPT/plots_Rao_2014_IMR90_full_betweenness/pvals_betweenness.csv", index_col=0)
df

    a != b  a > b  a < b chr       a         b
0    0.301  0.158  0.842  14  1_TssA     Bound
1    0.000  0.000  1.000  14  1_TssA  universe
2    0.264  0.862  0.138  14   7_Enh     Bound
3    0.000  0.000  1.000  14   7_Enh  universe
4    0.093  0.959  0.041   6  1_TssA     Bound
5    0.637  0.327  0.673   6  1_TssA  universe
6    0.007  0.993  0.007   6   7_Enh     Bound
7    0.189  0.917  0.083   6   7_Enh  universe
8    0.000  1.000  0.000  21  1_TssA     Bound
9    0.013  0.995  0.005  21  1_TssA  universe
10   0.004  0.998  0.002  21   7_Enh     Bound
11   0.033  0.985  0.015  21   7_Enh  universe
12   0.019  0.991  0.009  12  1_TssA     Bound
13   0.059  0.977  0.023  12  1_TssA  universe
14   0.177  0.905  0.095  12   7_Enh     Bound
15   0.062  0.032  0.968  12   7_Enh  universe
16   0.223  0.124  0.876   2  1_TssA     Bound
17   0.092  0.045  0.955   2  1_TssA  universe
18   0.915  0.481  0.519   2   7_Enh     Bound
19   0.702  0.650  0.350   2   7_Enh  universe
20   0.051  0.974  0.026   9  1_TssA     Bound
21   0.244  0.873  0.127   9  1_TssA  universe
22   0.326  0.852  0.148   9   7_Enh     Bound
23   0.032  0.017  0.983   9   7_Enh  universe
24     NaN    NaN    NaN   Y  1_TssA     Bound
25   0.159  0.883  0.000   Y  1_TssA  universe
26     NaN    NaN    NaN   Y   7_Enh     Bound
27   0.429  0.188  0.811   Y   7_Enh  universe
28   0.242  0.861  0.139   1  1_TssA     Bound
29   0.016  0.010  0.990   1  1_TssA  universe
30   0.000  1.000  0.000   1   7_Enh     Bound
31   0.047  0.981  0.019   1   7_Enh  universe
32   0.334  0.824  0.176  17  1_TssA     Bound
33   0.692  0.645  0.355  17  1_TssA  universe
34   0.000  1.000  0.000  17   7_Enh     Bound
35   0.000  1.000  0.000  17   7_Enh  universe
36   0.144  0.920  0.080   3  1_TssA     Bound
37   0.484  0.765  0.235   3  1_TssA  universe
38   0.309  0.141  0.859   3   7_Enh     Bound
39   0.000  0.000  1.000   3   7_Enh  universe
40   0.441  0.222  0.778  11  1_TssA     Bound
41   0.136  0.066  0.934  11  1_TssA  universe
42   0.673  0.675  0.325  11   7_Enh     Bound
43   0.181  0.916  0.084  11   7_Enh  universe
44   0.195  0.892  0.108  10  1_TssA     Bound
45   0.146  0.937  0.063  10  1_TssA  universe
46   0.843  0.572  0.428  10   7_Enh     Bound
47   0.067  0.031  0.969  10   7_Enh  universe
48   0.797  0.622  0.378   5  1_TssA     Bound
49   0.092  0.043  0.957   5  1_TssA  universe
50   0.281  0.135  0.865   5   7_Enh     Bound
51   0.000  0.000  1.000   5   7_Enh  universe
52   0.000  1.000  0.000   8  1_TssA     Bound
53   0.000  1.000  0.000   8  1_TssA  universe
54   0.005  0.996  0.004   8   7_Enh     Bound
55   0.005  0.999  0.001   8   7_Enh  universe
56   0.822  0.411  0.589   7  1_TssA     Bound
57   0.595  0.276  0.724   7  1_TssA  universe
58   0.830  0.429  0.571   7   7_Enh     Bound
59   0.174  0.086  0.914   7   7_Enh  universe
60   0.000  1.000  0.000   X  1_TssA     Bound
61   0.012  0.996  0.004   X  1_TssA  universe
62   0.000  1.000  0.000   X   7_Enh     Bound
63   0.472  0.223  0.777   X   7_Enh  universe
64   0.014  0.989  0.011  18  1_TssA     Bound
65   0.007  0.999  0.001  18  1_TssA  universe
66   0.139  0.921  0.079  18   7_Enh     Bound
67   0.379  0.809  0.191  18   7_Enh  universe
68   0.659  0.343  0.657   4  1_TssA     Bound
69   0.268  0.133  0.867   4  1_TssA  universe
70   0.410  0.215  0.785   4   7_Enh     Bound
71   0.000  0.000  1.000   4   7_Enh  universe
72   0.320  0.823  0.177  20  1_TssA     Bound
73   0.068  0.038  0.962  20  1_TssA  universe
74   0.231  0.882  0.118  20   7_Enh     Bound
75   0.001  0.001  0.999  20   7_Enh  universe
76   0.000  1.000  0.000  22  1_TssA     Bound
77   0.002  1.000  0.000  22  1_TssA  universe
78   0.000  1.000  0.000  22   7_Enh     Bound
79   0.701  0.360  0.640  22   7_Enh  universe
80   0.137  0.929  0.071  15  1_TssA     Bound
81   0.841  0.578  0.422  15  1_TssA  universe
82   0.112  0.954  0.046  15   7_Enh     Bound
83   0.982  0.470  0.530  15   7_Enh  universe
84   0.538  0.728  0.272  19  1_TssA     Bound
85   0.386  0.180  0.820  19  1_TssA  universe
86   0.000  1.000  0.000  19   7_Enh     Bound
87   0.000  1.000  0.000  19   7_Enh  universe
88   0.507  0.264  0.736  13  1_TssA     Bound
89   0.226  0.120  0.880  13  1_TssA  universe
90   0.627  0.675  0.325  13   7_Enh     Bound
91   0.085  0.965  0.035  13   7_Enh  universe
92   0.329  0.176  0.824  16  1_TssA     Bound
93   0.000  0.000  1.000  16  1_TssA  universe
94   0.035  0.974  0.026  16   7_Enh     Bound
95   0.076  0.973  0.027  16   7_Enh  universe

In [32]:
sig_df = df[(df["a != b"] < 0.05)|(df["a > b"] < 0.05) | (df["a < b"] < 0.05)]
print(f"Number of rows with at least one significant test: {len(sig_df)}")
sig_df

Number of rows with at least one significant test: 46

    a != b  a > b  a < b chr       a         b
1    0.000  0.000  1.000  14  1_TssA  universe
3    0.000  0.000  1.000  14   7_Enh  universe
4    0.093  0.959  0.041   6  1_TssA     Bound
6    0.007  0.993  0.007   6   7_Enh     Bound
8    0.000  1.000  0.000  21  1_TssA     Bound
9    0.013  0.995  0.005  21  1_TssA  universe
10   0.004  0.998  0.002  21   7_Enh     Bound
11   0.033  0.985  0.015  21   7_Enh  universe
12   0.019  0.991  0.009  12  1_TssA     Bound
13   0.059  0.977  0.023  12  1_TssA  universe
15   0.062  0.032  0.968  12   7_Enh  universe
17   0.092  0.045  0.955   2  1_TssA  universe
20   0.051  0.974  0.026   9  1_TssA     Bound
23   0.032  0.017  0.983   9   7_Enh  universe
25   0.159  0.883  0.000   Y  1_TssA  universe
29   0.016  0.010  0.990   1  1_TssA  universe
30   0.000  1.000  0.000   1   7_Enh     Bound
31   0.047  0.981  0.019   1   7_Enh  universe
34   0.000  1.000  0.000  17   7_Enh     Bound
35   0.000  1.000  0.000  17   7_Enh  universe
39   0.000  0.000  1.000   3   7_Enh  universe
47   0.067  0.031  0.969  10   7_Enh  universe
49   0.092  0.043  0.957   5  1_TssA  universe
51   0.000  0.000  1.000   5   7_Enh  universe
52   0.000  1.000  0.000   8  1_TssA     Bound
53   0.000  1.000  0.000   8  1_TssA  universe
54   0.005  0.996  0.004   8   7_Enh     Bound
55   0.005  0.999  0.001   8   7_Enh  universe
60   0.000  1.000  0.000   X  1_TssA     Bound
61   0.012  0.996  0.004   X  1_TssA  universe
62   0.000  1.000  0.000   X   7_Enh     Bound
64   0.014  0.989  0.011  18  1_TssA     Bound
65   0.007  0.999  0.001  18  1_TssA  universe
71   0.000  0.000  1.000   4   7_Enh  universe
73   0.068  0.038  0.962  20  1_TssA  universe
75   0.001  0.001  0.999  20   7_Enh  universe
76   0.000  1.000  0.000  22  1_TssA     Bound
77   0.002  1.000  0.000  22  1_TssA  universe
78   0.000  1.000  0.000  22   7_Enh     Bound
82   0.112  0.954  0.046  15   7_Enh     Bound
86   0.000  1.000  0.000  19   7_Enh     Bound
87   0.000  1.000  0.000  19   7_Enh  universe
91   0.085  0.965  0.035  13   7_Enh  universe
93   0.000  0.000  1.000  16  1_TssA  universe
94   0.035  0.974  0.026  16   7_Enh     Bound
95   0.076  0.973  0.027  16   7_Enh  universe

In [33]:
sig_df.loc[:, ["a > b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a > b"]]
sig_df.loc[:, ["a < b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a < b"]]
sig_df.loc[:, ["a != b"]] = [1 if val  < 0.05 else 0 for val in sig_df["a != b"]]
sig_df.groupby(["a", "b"]).sum()

/home/stefano/.local/lib/python3.10/site-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

                 a != b  a > b  a < b
a      b
1_TssA Bound          6      0      8
       universe       8      6      7
7_Enh  Bound          9      0     10
       universe      11      8      7

In [18]:
sig_df[(sig_df["a"] == "1_TssA") & (sig_df["b"] == "Bound") & (sig_df["a < b"] == 1)].sort_values("chr")

    a != b  a > b  a < b chr       a      b
28       1      0      1   1  1_TssA  Bound
44       1      0      1  10  1_TssA  Bound
40       1      0      1  11  1_TssA  Bound
12       1      0      1  12  1_TssA  Bound
88       1      0      1  13  1_TssA  Bound
0        1      0      1  14  1_TssA  Bound
80       1      0      1  15  1_TssA  Bound
64       1      0      1  18  1_TssA  Bound
16       1      0      1   2  1_TssA  Bound
72       1      0      1  20  1_TssA  Bound
8        1      0      1  21  1_TssA  Bound
76       1      0      1  22  1_TssA  Bound
36       1      0      1   3  1_TssA  Bound
68       1      0      1   4  1_TssA  Bound
48       1      0      1   5  1_TssA  Bound
4        1      0      1   6  1_TssA  Bound
56       1      0      1   7  1_TssA  Bound
52       1      0      1   8  1_TssA  Bound
20       1      0      1   9  1_TssA  Bound
60       1      0      1   X  1_TssA  Bound

In [20]:
sig_df[(sig_df["a"] == "7_Enh") & (sig_df["b"] == "Bound") & (sig_df["a < b"] == 1)].sort_values("chr")

    a != b  a > b  a < b chr      a      b
30       1      0      1   1  7_Enh  Bound
46       1      0      1  10  7_Enh  Bound
42       1      0      1  11  7_Enh  Bound
14       1      0      1  12  7_Enh  Bound
90       1      0      1  13  7_Enh  Bound
2        1      0      1  14  7_Enh  Bound
82       1      0      1  15  7_Enh  Bound
34       1      0      1  17  7_Enh  Bound
66       1      0      1  18  7_Enh  Bound
18       1      0      1   2  7_Enh  Bound
74       1      0      1  20  7_Enh  Bound
10       1      0      1  21  7_Enh  Bound
38       1      0      1   3  7_Enh  Bound
70       1      0      1   4  7_Enh  Bound
50       1      0      1   5  7_Enh  Bound
6        1      0      1   6  7_Enh  Bound
58       1      0      1   7  7_Enh  Bound
54       1      0      1   8  7_Enh  Bound
22       1      0      1   9  7_Enh  Bound
62       1      0      1   X  7_Enh  Bound

In [ ]:
bigger = sig_df.groupby("chr")["a > b"].count()
smaller = sig_df.groupby("chr")["a < b"].count()
differ = sig_df.groupby("chr")["a != b"].count()

chr_df = pd.DataFrame([bigger, smaller, differ]).T
chr_df

In [ ]:
sig_df.sort_values("chr")[0:63]

In [ ]:
upset_df = sig_df.set_index(["a != b", "a < b", "a > b", "a", "b"])
upset_df

In [ ]:
up.plot(upset_df)  
pyplot.show()